name: Run Tests, Coverage, and Linting

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and nmap
      run: |
        sudo apt-get update
        sudo apt-get install -y nmap
        python -m pip install --upgrade pip
        pip install coverage flake8 pylint

    - name: Run flake8 on src and tests
      continue-on-error: true
      run: |
        flake8 src/ tests/ | tee flake8-report.txt

    - name: Run pylint on src and tests, enforce minimum score
      continue-on-error: true
      run: |
        FILES="src tests"
        pylint $FILES | tee pylint-report.txt
        SCORE=$(pylint $FILES | tail -n 2 | grep 'Your code has been rated at' | awk '{print $7}' | cut -d/ -f1)
        echo "Pylint score: $SCORE"
        if (( $(echo "$SCORE < 9.0" | bc -l) )); then
          echo "Pylint score is too low. Minimum required is 9.0"
          exit 1
        fi

    - name: Run tests with coverage
      continue-on-error: true
      run: |
        coverage run --source=src -m unittest discover -s tests
        coverage report -m
        coverage html

    - name: Upload all report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: |
          flake8-report.txt
          pylint-report.txt
          htmlcov/
